version: '3.8'

services:
  web:
    build: .
    image: cicd-app:latest
    container_name: cicd-app
    ports:
      - 5000:80
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:17
    platform: linux/amd64  # За Intel Mac
    container_name: postgres-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"

volumes:
  postgres_data: